<?php

use CrowdinApiClient\Model\Language;
use CrowdinApiClient\ModelCollection;

$data = new ModelCollection();
$data->setPagination([
    'offset' => 0,
    'limit' => 500,
]);

$items = [
    new Language(['id' => 'ach', 'name' => 'Acholi']),
    new Language(['id' => 'aa', 'name' => 'Afar']),
    new Language(['id' => 'af', 'name' => 'Afrikaans']),
    new Language(['id' => 'ak', 'name' => 'Akan']),
    new Language(['id' => 'tw', 'name' => 'Akan, Twi']),
    new Language(['id' => 'sq', 'name' => 'Albanian']),
    new Language(['id' => 'am', 'name' => 'Amharic']),
    new Language(['id' => 'ar', 'name' => 'Arabic']),
    new Language(['id' => 'ar-BH', 'name' => 'Arabic, Bahrain']),
    new Language(['id' => 'ar-EG', 'name' => 'Arabic, Egypt']),
    new Language(['id' => 'ar-SA', 'name' => 'Arabic, Saudi Arabia']),
    new Language(['id' => 'ar-YE', 'name' => 'Arabic, Yemen']),
    new Language(['id' => 'an', 'name' => 'Aragonese']),
    new Language(['id' => 'hy-AM', 'name' => 'Armenian']),
    new Language(['id' => 'frp', 'name' => 'Arpitan']),
    new Language(['id' => 'as', 'name' => 'Assamese']),
    new Language(['id' => 'ast', 'name' => 'Asturian']),
    new Language(['id' => 'tay', 'name' => 'Atayal']),
    new Language(['id' => 'av', 'name' => 'Avaric']),
    new Language(['id' => 'ae', 'name' => 'Avestan']),
    new Language(['id' => 'ay', 'name' => 'Aymara']),
    new Language(['id' => 'az', 'name' => 'Azerbaijani']),
    new Language(['id' => 'ban', 'name' => 'Balinese']),
    new Language(['id' => 'bal', 'name' => 'Balochi']),
    new Language(['id' => 'bm', 'name' => 'Bambara']),
    new Language(['id' => 'ba', 'name' => 'Bashkir']),
    new Language(['id' => 'eu', 'name' => 'Basque']),
    new Language(['id' => 'be', 'name' => 'Belarusian']),
    new Language(['id' => 'bn', 'name' => 'Bengali']),
    new Language(['id' => 'bn-IN', 'name' => 'Bengali, India']),
    new Language(['id' => 'ber', 'name' => 'Berber']),
    new Language(['id' => 'bh', 'name' => 'Bihari']),
    new Language(['id' => 'bfo', 'name' => 'Birifor']),
    new Language(['id' => 'bi', 'name' => 'Bislama']),
    new Language(['id' => 'bs', 'name' => 'Bosnian']),
    new Language(['id' => 'br-FR', 'name' => 'Breton']),
    new Language(['id' => 'bg', 'name' => 'Bulgarian']),
    new Language(['id' => 'my', 'name' => 'Burmese']),
    new Language(['id' => 'ca', 'name' => 'Catalan']),
    new Language(['id' => 'ceb', 'name' => 'Cebuano']),
    new Language(['id' => 'ch', 'name' => 'Chamorro']),
    new Language(['id' => 'ce', 'name' => 'Chechen']),
    new Language(['id' => 'chr', 'name' => 'Cherokee']),
    new Language(['id' => 'ny', 'name' => 'Chewa']),
    new Language(['id' => 'zh-CN', 'name' => 'Chinese Simplified']),
    new Language(['id' => 'zh-TW', 'name' => 'Chinese Traditional']),
    new Language(['id' => 'zh-HK', 'name' => 'Chinese Traditional, Hong Kong']),
    new Language(['id' => 'zh-MO', 'name' => 'Chinese Traditional, Macau']),
    new Language(['id' => 'zh-SG', 'name' => 'Chinese Traditional, Singapore']),
    new Language(['id' => 'cv', 'name' => 'Chuvash']),
    new Language(['id' => 'kw', 'name' => 'Cornish']),
    new Language(['id' => 'co', 'name' => 'Corsican']),
    new Language(['id' => 'cr', 'name' => 'Cree']),
    new Language(['id' => 'hr', 'name' => 'Croatian']),
    new Language(['id' => 'cs', 'name' => 'Czech']),
    new Language(['id' => 'da', 'name' => 'Danish']),
    new Language(['id' => 'fa-AF', 'name' => 'Dari']),
    new Language(['id' => 'dv', 'name' => 'Dhivehi']),
    new Language(['id' => 'nl', 'name' => 'Dutch']),
    new Language(['id' => 'nl-BE', 'name' => 'Dutch, Belgium']),
    new Language(['id' => 'nl-SR', 'name' => 'Dutch, Suriname']),
    new Language(['id' => 'dz', 'name' => 'Dzongkha']),
    new Language(['id' => 'en', 'name' => 'English']),
    new Language(['id' => 'en-UD', 'name' => 'English (upside down)']),
    new Language(['id' => 'en-AR', 'name' => 'English, Arabia']),
    new Language(['id' => 'en-AU', 'name' => 'English, Australia']),
    new Language(['id' => 'en-BZ', 'name' => 'English, Belize']),
    new Language(['id' => 'en-CA', 'name' => 'English, Canada']),
    new Language(['id' => 'en-CB', 'name' => 'English, Caribbean']),
    new Language(['id' => 'en-CN', 'name' => 'English, China']),
    new Language(['id' => 'en-DK', 'name' => 'English, Denmark']),
    new Language(['id' => 'en-HK', 'name' => 'English, Hong Kong']),
    new Language(['id' => 'en-IN', 'name' => 'English, India']),
    new Language(['id' => 'en-ID', 'name' => 'English, Indonesia']),
    new Language(['id' => 'en-IE', 'name' => 'English, Ireland']),
    new Language(['id' => 'en-JM', 'name' => 'English, Jamaica']),
    new Language(['id' => 'en-JA', 'name' => 'English, Japan']),
    new Language(['id' => 'en-MY', 'name' => 'English, Malaysia']),
    new Language(['id' => 'en-NZ', 'name' => 'English, New Zealand']),
    new Language(['id' => 'en-NO', 'name' => 'English, Norway']),
    new Language(['id' => 'en-PH', 'name' => 'English, Philippines']),
    new Language(['id' => 'en-PR', 'name' => 'English, Puerto Rico']),
    new Language(['id' => 'en-SG', 'name' => 'English, Singapore']),
    new Language(['id' => 'en-ZA', 'name' => 'English, South Africa']),
    new Language(['id' => 'en-SE', 'name' => 'English, Sweden']),
    new Language(['id' => 'en-GB', 'name' => 'English, United Kingdom']),
    new Language(['id' => 'en-US', 'name' => 'English, United States']),
    new Language(['id' => 'en-ZW', 'name' => 'English, Zimbabwe']),
    new Language(['id' => 'eo', 'name' => 'Esperanto']),
    new Language(['id' => 'et', 'name' => 'Estonian']),
    new Language(['id' => 'ee', 'name' => 'Ewe']),
    new Language(['id' => 'fo', 'name' => 'Faroese']),
    new Language(['id' => 'fj', 'name' => 'Fijian']),
    new Language(['id' => 'fil', 'name' => 'Filipino']),
    new Language(['id' => 'fi', 'name' => 'Finnish']),
    new Language(['id' => 'vls-BE', 'name' => 'Flemish']),
    new Language(['id' => 'fra-DE', 'name' => 'Franconian']),
    new Language(['id' => 'fr', 'name' => 'French']),
    new Language(['id' => 'fr-BE', 'name' => 'French, Belgium']),
    new Language(['id' => 'fr-CA', 'name' => 'French, Canada']),
    new Language(['id' => 'fr-LU', 'name' => 'French, Luxembourg']),
    new Language(['id' => 'fr-QC', 'name' => 'French, Quebec']),
    new Language(['id' => 'fr-CH', 'name' => 'French, Switzerland']),
    new Language(['id' => 'fy-NL', 'name' => 'Frisian']),
    new Language(['id' => 'fur-IT', 'name' => 'Friulian']),
    new Language(['id' => 'ff', 'name' => 'Fula']),
    new Language(['id' => 'gaa', 'name' => 'Ga']),
    new Language(['id' => 'gl', 'name' => 'Galician']),
    new Language(['id' => 'ka', 'name' => 'Georgian']),
    new Language(['id' => 'de', 'name' => 'German']),
    new Language(['id' => 'de-AT', 'name' => 'German, Austria']),
    new Language(['id' => 'de-BE', 'name' => 'German, Belgium']),
    new Language(['id' => 'de-LI', 'name' => 'German, Liechtenstein']),
    new Language(['id' => 'de-LU', 'name' => 'German, Luxembourg']),
    new Language(['id' => 'de-CH', 'name' => 'German, Switzerland']),
    new Language(['id' => 'got', 'name' => 'Gothic']),
    new Language(['id' => 'el', 'name' => 'Greek']),
    new Language(['id' => 'el-CY', 'name' => 'Greek, Cyprus']),
    new Language(['id' => 'kl', 'name' => 'Greenlandic']),
    new Language(['id' => 'gn', 'name' => 'Guarani']),
    new Language(['id' => 'gu-IN', 'name' => 'Gujarati']),
    new Language(['id' => 'ht', 'name' => 'Haitian Creole']),
    new Language(['id' => 'ha', 'name' => 'Hausa']),
    new Language(['id' => 'haw', 'name' => 'Hawaiian']),
    new Language(['id' => 'he', 'name' => 'Hebrew']),
    new Language(['id' => 'hz', 'name' => 'Herero']),
    new Language(['id' => 'hil', 'name' => 'Hiligaynon']),
    new Language(['id' => 'hi', 'name' => 'Hindi']),
    new Language(['id' => 'ho', 'name' => 'Hiri Motu']),
    new Language(['id' => 'hmn', 'name' => 'Hmong']),
    new Language(['id' => 'hu', 'name' => 'Hungarian']),
    new Language(['id' => 'is', 'name' => 'Icelandic']),
    new Language(['id' => 'ido', 'name' => 'Ido']),
    new Language(['id' => 'ig', 'name' => 'Igbo']),
    new Language(['id' => 'ilo', 'name' => 'Ilokano']),
    new Language(['id' => 'id', 'name' => 'Indonesian']),
    new Language(['id' => 'iu', 'name' => 'Inuktitut']),
    new Language(['id' => 'ga-IE', 'name' => 'Irish']),
    new Language(['id' => 'it', 'name' => 'Italian']),
    new Language(['id' => 'it-CH', 'name' => 'Italian, Switzerland']),
    new Language(['id' => 'ja', 'name' => 'Japanese']),
    new Language(['id' => 'jv', 'name' => 'Javanese']),
    new Language(['id' => 'quc', 'name' => 'K\'iche\'']),
    new Language(['id' => 'kab', 'name' => 'Kabyle']),
    new Language(['id' => 'kn', 'name' => 'Kannada']),
    new Language(['id' => 'pam', 'name' => 'Kapampangan']),
    new Language(['id' => 'ks', 'name' => 'Kashmiri']),
    new Language(['id' => 'ks-PK', 'name' => 'Kashmiri, Pakistan']),
    new Language(['id' => 'csb', 'name' => 'Kashubian']),
    new Language(['id' => 'kk', 'name' => 'Kazakh']),
    new Language(['id' => 'km', 'name' => 'Khmer']),
    new Language(['id' => 'rw', 'name' => 'Kinyarwanda']),
    new Language(['id' => 'tlh-AA', 'name' => 'Klingon']),
    new Language(['id' => 'kv', 'name' => 'Komi']),
    new Language(['id' => 'kg', 'name' => 'Kongo']),
    new Language(['id' => 'kok', 'name' => 'Konkani']),
    new Language(['id' => 'ko', 'name' => 'Korean']),
    new Language(['id' => 'ku', 'name' => 'Kurdish']),
    new Language(['id' => 'kmr', 'name' => 'Kurmanji (Kurdish)']),
    new Language(['id' => 'kj', 'name' => 'Kwanyama']),
    new Language(['id' => 'ky', 'name' => 'Kyrgyz']),
    new Language(['id' => 'lo', 'name' => 'Lao']),
    new Language(['id' => 'la-LA', 'name' => 'Latin']),
    new Language(['id' => 'lv', 'name' => 'Latvian']),
    new Language(['id' => 'lij', 'name' => 'Ligurian']),
    new Language(['id' => 'li', 'name' => 'Limburgish']),
    new Language(['id' => 'ln', 'name' => 'Lingala']),
    new Language(['id' => 'lt', 'name' => 'Lithuanian']),
    new Language(['id' => 'jbo', 'name' => 'Lojban']),
    new Language(['id' => 'lol', 'name' => 'LOLCAT']),
    new Language(['id' => 'nds', 'name' => 'Low German']),
    new Language(['id' => 'dsb-DE', 'name' => 'Lower Sorbian']),
    new Language(['id' => 'lg', 'name' => 'Luganda']),
    new Language(['id' => 'luy', 'name' => 'Luhya']),
    new Language(['id' => 'lb', 'name' => 'Luxembourgish']),
    new Language(['id' => 'mk', 'name' => 'Macedonian']),
    new Language(['id' => 'mai', 'name' => 'Maithili']),
    new Language(['id' => 'mg', 'name' => 'Malagasy']),
    new Language(['id' => 'ms', 'name' => 'Malay']),
    new Language(['id' => 'ms-BN', 'name' => 'Malay, Brunei']),
    new Language(['id' => 'ml-IN', 'name' => 'Malayalam']),
    new Language(['id' => 'mt', 'name' => 'Maltese']),
    new Language(['id' => 'gv', 'name' => 'Manx']),
    new Language(['id' => 'mi', 'name' => 'Maori']),
    new Language(['id' => 'arn', 'name' => 'Mapudungun']),
    new Language(['id' => 'mr', 'name' => 'Marathi']),
    new Language(['id' => 'mh', 'name' => 'Marshallese']),
    new Language(['id' => 'moh', 'name' => 'Mohawk']),
    new Language(['id' => 'mn', 'name' => 'Mongolian']),
    new Language(['id' => 'sr-Cyrl-ME', 'name' => 'Montenegrin (Cyrillic)']),
    new Language(['id' => 'me', 'name' => 'Montenegrin (Latin)']),
    new Language(['id' => 'mos', 'name' => 'Mossi']),
    new Language(['id' => 'na', 'name' => 'Nauru']),
    new Language(['id' => 'ng', 'name' => 'Ndonga']),
    new Language(['id' => 'ne-NP', 'name' => 'Nepali']),
    new Language(['id' => 'ne-IN', 'name' => 'Nepali, India']),
    new Language(['id' => 'pcm', 'name' => 'Nigerian Pidgin']),
    new Language(['id' => 'se', 'name' => 'Northern Sami']),
    new Language(['id' => 'nso', 'name' => 'Northern Sotho']),
    new Language(['id' => 'no', 'name' => 'Norwegian']),
    new Language(['id' => 'nb', 'name' => 'Norwegian Bokmal']),
    new Language(['id' => 'nn-NO', 'name' => 'Norwegian Nynorsk']),
    new Language(['id' => 'oc', 'name' => 'Occitan']),
    new Language(['id' => 'or', 'name' => 'Odia']),
    new Language(['id' => 'oj', 'name' => 'Ojibwe']),
    new Language(['id' => 'om', 'name' => 'Oromo']),
    new Language(['id' => 'os', 'name' => 'Ossetian']),
    new Language(['id' => 'pi', 'name' => 'Pali']),
    new Language(['id' => 'pap', 'name' => 'Papiamento']),
    new Language(['id' => 'ps', 'name' => 'Pashto']),
    new Language(['id' => 'fa', 'name' => 'Persian']),
    new Language(['id' => 'en-PT', 'name' => 'Pirate English']),
    new Language(['id' => 'pl', 'name' => 'Polish']),
    new Language(['id' => 'pt-PT', 'name' => 'Portuguese']),
    new Language(['id' => 'pt-BR', 'name' => 'Portuguese, Brazilian']),
    new Language(['id' => 'pa-IN', 'name' => 'Punjabi']),
    new Language(['id' => 'pa-PK', 'name' => 'Punjabi, Pakistan']),
    new Language(['id' => 'qu', 'name' => 'Quechua']),
    new Language(['id' => 'qya-AA', 'name' => 'Quenya']),
    new Language(['id' => 'ro', 'name' => 'Romanian']),
    new Language(['id' => 'rm-CH', 'name' => 'Romansh']),
    new Language(['id' => 'rn', 'name' => 'Rundi']),
    new Language(['id' => 'ru', 'name' => 'Russian']),
    new Language(['id' => 'ru-BY', 'name' => 'Russian, Belarus']),
    new Language(['id' => 'ru-MD', 'name' => 'Russian, Moldova']),
    new Language(['id' => 'ru-UA', 'name' => 'Russian, Ukraine']),
    new Language(['id' => 'ry-UA', 'name' => 'Rusyn']),
    new Language(['id' => 'sah', 'name' => 'Sakha']),
    new Language(['id' => 'sg', 'name' => 'Sango']),
    new Language(['id' => 'sa', 'name' => 'Sanskrit']),
    new Language(['id' => 'sat', 'name' => 'Santali']),
    new Language(['id' => 'sc', 'name' => 'Sardinian']),
    new Language(['id' => 'sco', 'name' => 'Scots']),
    new Language(['id' => 'gd', 'name' => 'Scottish Gaelic']),
    new Language(['id' => 'sr', 'name' => 'Serbian (Cyrillic)']),
    new Language(['id' => 'sr-CS', 'name' => 'Serbian (Latin)']),
    new Language(['id' => 'sh', 'name' => 'Serbo-Croatian']),
    new Language(['id' => 'crs', 'name' => 'Seychellois Creole']),
    new Language(['id' => 'sn', 'name' => 'Shona']),
    new Language(['id' => 'ii', 'name' => 'Sichuan Yi']),
    new Language(['id' => 'sd', 'name' => 'Sindhi']),
    new Language(['id' => 'si-LK', 'name' => 'Sinhala']),
    new Language(['id' => 'sk', 'name' => 'Slovak']),
    new Language(['id' => 'sl', 'name' => 'Slovenian']),
    new Language(['id' => 'so', 'name' => 'Somali']),
    new Language(['id' => 'son', 'name' => 'Songhay']),
    new Language(['id' => 'ckb', 'name' => 'Sorani (Kurdish)']),
    new Language(['id' => 'nr', 'name' => 'Southern Ndebele']),
    new Language(['id' => 'sma', 'name' => 'Southern Sami']),
    new Language(['id' => 'st', 'name' => 'Southern Sotho']),
    new Language(['id' => 'es-ES', 'name' => 'Spanish']),
    new Language(['id' => 'es-EM', 'name' => 'Spanish (Modern)']),
    new Language(['id' => 'es-AR', 'name' => 'Spanish, Argentina']),
    new Language(['id' => 'es-BO', 'name' => 'Spanish, Bolivia']),
    new Language(['id' => 'es-CL', 'name' => 'Spanish, Chile']),
    new Language(['id' => 'es-CO', 'name' => 'Spanish, Colombia']),
    new Language(['id' => 'es-CR', 'name' => 'Spanish, Costa Rica']),
    new Language(['id' => 'es-DO', 'name' => 'Spanish, Dominican Republic']),
    new Language(['id' => 'es-EC', 'name' => 'Spanish, Ecuador']),
    new Language(['id' => 'es-SV', 'name' => 'Spanish, El Salvador']),
    new Language(['id' => 'es-GT', 'name' => 'Spanish, Guatemala']),
    new Language(['id' => 'es-HN', 'name' => 'Spanish, Honduras']),
    new Language(['id' => 'es-419', 'name' => 'Spanish, Latin America']),
    new Language(['id' => 'es-MX', 'name' => 'Spanish, Mexico']),
    new Language(['id' => 'es-NI', 'name' => 'Spanish, Nicaragua']),
    new Language(['id' => 'es-PA', 'name' => 'Spanish, Panama']),
    new Language(['id' => 'es-PY', 'name' => 'Spanish, Paraguay']),
    new Language(['id' => 'es-PE', 'name' => 'Spanish, Peru']),
    new Language(['id' => 'es-PR', 'name' => 'Spanish, Puerto Rico']),
    new Language(['id' => 'es-US', 'name' => 'Spanish, United States']),
    new Language(['id' => 'es-UY', 'name' => 'Spanish, Uruguay']),
    new Language(['id' => 'es-VE', 'name' => 'Spanish, Venezuela']),
    new Language(['id' => 'su', 'name' => 'Sundanese']),
    new Language(['id' => 'sw', 'name' => 'Swahili']),
    new Language(['id' => 'sw-KE', 'name' => 'Swahili, Kenya']),
    new Language(['id' => 'sw-TZ', 'name' => 'Swahili, Tanzania']),
    new Language(['id' => 'ss', 'name' => 'Swati']),
    new Language(['id' => 'sv-SE', 'name' => 'Swedish']),
    new Language(['id' => 'sv-FI', 'name' => 'Swedish, Finland']),
    new Language(['id' => 'syc', 'name' => 'Syriac']),
    new Language(['id' => 'tl', 'name' => 'Tagalog']),
    new Language(['id' => 'ty', 'name' => 'Tahitian']),
    new Language(['id' => 'tg', 'name' => 'Tajik']),
    new Language(['id' => 'tzl', 'name' => 'Talossan']),
    new Language(['id' => 'ta', 'name' => 'Tamil']),
    new Language(['id' => 'tt-RU', 'name' => 'Tatar']),
    new Language(['id' => 'te', 'name' => 'Telugu']),
    new Language(['id' => 'kdh', 'name' => 'Tem (Kotokoli)']),
    new Language(['id' => 'th', 'name' => 'Thai']),
    new Language(['id' => 'bo-BT', 'name' => 'Tibetan']),
    new Language(['id' => 'ti', 'name' => 'Tigrinya']),
    new Language(['id' => 'ts', 'name' => 'Tsonga']),
    new Language(['id' => 'tn', 'name' => 'Tswana']),
    new Language(['id' => 'tr', 'name' => 'Turkish']),
    new Language(['id' => 'tr-CY', 'name' => 'Turkish, Cyprus']),
    new Language(['id' => 'tk', 'name' => 'Turkmen']),
    new Language(['id' => 'uk', 'name' => 'Ukrainian']),
    new Language(['id' => 'hsb-DE', 'name' => 'Upper Sorbian']),
    new Language(['id' => 'ur-IN', 'name' => 'Urdu (India)']),
    new Language(['id' => 'ur-PK', 'name' => 'Urdu (Pakistan)']),
    new Language(['id' => 'ug', 'name' => 'Uyghur']),
    new Language(['id' => 'uz', 'name' => 'Uzbek']),
    new Language(['id' => 'val-ES', 'name' => 'Valencian']),
    new Language(['id' => 've', 'name' => 'Venda']),
    new Language(['id' => 'vec', 'name' => 'Venetian']),
    new Language(['id' => 'vi', 'name' => 'Vietnamese']),
    new Language(['id' => 'wa', 'name' => 'Walloon']),
    new Language(['id' => 'cy', 'name' => 'Welsh']),
    new Language(['id' => 'wo', 'name' => 'Wolof']),
    new Language(['id' => 'xh', 'name' => 'Xhosa']),
    new Language(['id' => 'yi', 'name' => 'Yiddish']),
    new Language(['id' => 'yo', 'name' => 'Yoruba']),
    new Language(['id' => 'zea', 'name' => 'Zeelandic']),
    new Language(['id' => 'zu', 'name' => 'Zulu']),
];

foreach ($items as $item) {
    $data->add($item);
}

return $data;
